# Generated by Django 4.0.6 on 2022-07-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='logons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.persons')),
            ],
        ),
        migrations.CreateModel(
            name='calls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='actual', max_length=255)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.persons')),
            ],
        ),
    ]
