# Generated by Django 4.0.6 on 2022-07-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calls',
            table='calls',
        ),
        migrations.AlterModelTable(
            name='logons',
            table='logons',
        ),
        migrations.AlterModelTable(
            name='persons',
            table='persons',
        ),
    ]
