# Generated by Django 4.0.6 on 2022-07-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_calls_table_alter_logons_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calls',
            old_name='person_id',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='logons',
            old_name='person_id',
            new_name='person',
        ),
    ]
